# Generated by Django 4.2.6 on 2023-10-15 10:49

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_code', models.CharField(max_length=255)),
                ('http_status_code', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_types', related_query_name='page_types_user_field', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page Type',
                'verbose_name_plural': 'Page Types',
            },
        ),
        migrations.CreateModel(
            name='PageContentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('status', models.BooleanField(default=False)),
                ('page_type', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_content', to='pages.pagetypemodel', verbose_name='Page Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_contents', related_query_name='review_user_field', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page Content',
                'verbose_name_plural': 'Page Contents',
                'db_table': 'page_review',
                'ordering': ['-created_at'],
            },
        ),
    ]
